language: php

php:
  - 7.2
  - 7.3

env:
  global:
    - DEFAULT=1

matrix:
  include:
    - php: 7.2
      env: PHPCS=1 DEFAULT=0

before_install:
  - phpenv config-rm xdebug.ini

install:
  - make install-dev

script:
  - if [[ $DEFAULT == 1 ]]; then make test; fi
  - if [[ $PHPCS == 1 ]]; then make check-cs; fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false
